---
# tasks file for apache

- name: install required packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - mariadb
  - mariadb-server

- name: enable mariadb service
  service:
    state: started
    enabled: yes
    name: httpd
