
- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ service_name }}"
    location: "{{ location }}"
    state: "{{ state }}"
    force: yes

- name: Create a virtual network
  azure_rm_virtualnetwork:
    name: "{{ vm_net }}"
    resource_group: "{{ service_name }}"
    address_prefixes_cidr:
        - "{{ net_prefix }}"
  when:
  - state == "present"

- name: Create a subnet
  azure_rm_subnet:
    name: "{{ vm_subnet }}"
    virtual_network_name: "{{ vm_net }}"
    resource_group: "{{ service_name }}"
    address_prefix_cidr: "{{ subnet_prefix }}"
  when:
  - state == "present"
