
- name: Azure init
  azure_rm_virtualmachine:
    resource_group: "{{ service_name }}"
    name: "{{ server_group }}{{ item }}"
    admin_username: "{{ user_id }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ user_id }}/.ssh/authorized_keys
        key_data: "{{ pub_key }}"
    image:
      offer: RHEL
      publisher: RedHat
      sku: '7.3'
      version: latest
  register: vm
  with_sequence: count="{{ server_qty }}"


- name: Show hostvars[inventory_hostname]
  debug: var=hostvars

- name: Show ansible_ssh_host variable in hostvars
  debug: var=vm

- name: Adding new instances to inventory
  add_host:
    hostname: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    groups: "{{ server_group }}"
  with_items: "{{ vm.results }}"

- name: Show group_names
  debug: var=group_names

- name: Show groups
  debug: var=groups
