

- name: Generate vm uuid
    command: uuidgen
    register: vm_uuid

- debug: msg="vm_uuid = {{ vm_uuid.stdout }}"

- name: Azure init
  azure_rm_virtualmachine:
    resource_group: "{{ service_name }}"
    name: "{{ vm_uuid.stdout }}{{ item }}"
    admin_username: "{{ user_id }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ user_id }}/.ssh/authorized_keys
        key_data: "{{ pub_key }}"
    vm_size: "{{ vmsize }}"
    image: "{{ image }}"
    open_ports: "{{ open_ports }}"
  register: vm
  with_sequence: count="{{ server_qty }}"


- name: Adding new instances to inventory
  add_host:
    hostname: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    groups: "{{ server_group }}"
  with_items: "{{ vm.results }}"
