---
- name: Launch 1 VM in Azure
  hosts: localhost
  connection: local
  tasks:
        - name: Launch a new VM named TEST in "{{ az_resourceGroupName }}"
          register: azure_vm 
          azure_rm_virtualmachine:
            resource_group: "{{ az_resourceGroupName }}"
            name: TESTRHEL000
            storage_account: "{{ az_storageAccountName }}"
            virtual_network_name : "{{ az_vNetName }}"
            admin_username: testadmin
            admin_password: test-password-012346789
            vm_size: "Standard_A1_v2"
            image:
                    offer: rhel-byol
                    publisher: redhat
                    sku: 'rhel74'
                    version: latest
        - debug: var=azure_vm 


