---
- name: Destroy 1 VM in Azure
  hosts: localhost
  connection: local
  tasks:
        - name: Destroy the VM named TEST in "{{ az_resourceGroupName }}"
          azure_rm_virtualmachine:
            resource_group: "{{ az_resourceGroupName }}"
            name: TESTRHEL000
            state: absent
            remove_on_absent:
                - all
