---
- name: Create Azure Resources
  hosts: localhost
  connection: local
  tasks:
        - name: Create a resource group named "{{ az_resourceGroupName }}" in "{{ az_location }}"
          register: state
          azure_rm_resourcegroup:
            name: "{{ az_resourceGroupName }}"
            location: "{{ az_location }}"
            tags:
                maintag: "{{ az_tagvalue }}"
                delete: never
        - debug: var=state

        - name: Create security group "{{ az_networkSecurityGroup }}"
          azure_rm_securitygroup:
            resource_group: "{{ az_resourceGroupName }}"
            name: "{{ az_networkSecurityGroup }}"
            purge_rules: no
            rules:
                  - name: 'AllowSSH'
                    protocol: Tcp
                    source_address_prefix: '*'
                    destination_port_range: 22
                    access: Allow
                    priority: 101
                    direction: Inbound
                  - name: 'AllowHTTP'
                    protocol: Tcp
                    source_address_prefix: '*'
                    destination_port_range: 80
                    access: Allow
                    priority: 102
                    direction: Inbound
                  - name: 'AllowHTPS'
                    protocol: Tcp
                    source_address_prefix: '*'
                    destination_port_range: 443
                    access: Allow
                    priority: 103
                    direction: Inbound
        - name: Create storage account "{{az_storageAccountName}}"
          azure_rm_storageaccount:
                  name: "{{az_storageAccountName}}"
                  resource_group: "{{ az_resourceGroupName }}"
                  type: Standard_LRS
                  tags:
                      maintag: "{{ az_tagvalue }}"
                      delete: on-exit
        - name: Create network "{{az_vNetName}}"
          azure_rm_virtualnetwork:
                  name: "{{az_vNetName}}"
                  resource_group: "{{ az_resourceGroupName }}"
                  address_prefixes_cidr:
                          - "{{az_subnetAddressPrefix}}"
                  tags:
                      maintag: "{{ az_tagvalue }}"
                      delete: on-exit

        - name: Create subnetwork "{{az_subnetName}}" "{{az_subnetAddressPrefix}}" for "{{az_vNetName}}"
          azure_rm_subnet:
                  name: "{{az_subnetName}}"
                  resource_group: "{{ az_resourceGroupName }}"
                  virtual_network_name: "{{az_vNetName}}"
                  address_prefix_cidr: "{{az_subnetAddressPrefix}}"
                  security_group_name: "{{ az_networkSecurityGroup }}"

